/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Muhammad Umer
 */
public class InstructorView extends javax.swing.JFrame {

    /**
     * Creates new form InstructorView
     */
    public InstructorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        quiztitlefield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        quizdescfield = new javax.swing.JTextField();
        createbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        maxmarksfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Quiz Generator");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 138, -1));
        getContentPane().add(quiztitlefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 67, 400, -1));

        jLabel2.setText("Quiz Title:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 70, -1, -1));

        jLabel3.setText("Quiz Description:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 101, -1, -1));
        getContentPane().add(quizdescfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 98, 400, -1));

        createbutton.setText("Create Quiz");
        createbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(createbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 199, -1, -1));

        jLabel4.setText("Total Marks:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 136, 81, -1));

        maxmarksfield.setText("Enter maximum achievable score in the quiz");
        maxmarksfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                maxmarksfieldFocusGained(evt);
            }
        });
        getContentPane().add(maxmarksfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 130, 232, -1));

        getAccessibleContext().setAccessibleName("Generating Quiz");

        setSize(new java.awt.Dimension(657, 294));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbuttonActionPerformed
        // TODO add your handling code here:
        String quiztitle=quiztitlefield.getText();
        String quizdesc=quizdescfield.getText();
        int maxmarks=Integer.parseInt(maxmarksfield.getText());
        //Quiz quiznew=new Quiz(quiztitle,quizdesc);
        CreatingQuizView cqv=new CreatingQuizView(quiztitle, quizdesc, maxmarks);
        cqv.setVisible(true);
        InstructorView.this.dispose();
    }//GEN-LAST:event_createbuttonActionPerformed

    private void maxmarksfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_maxmarksfieldFocusGained
        // TODO add your handling code here:
        maxmarksfield.setText("");
    }//GEN-LAST:event_maxmarksfieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField maxmarksfield;
    private javax.swing.JTextField quizdescfield;
    private javax.swing.JTextField quiztitlefield;
    // End of variables declaration//GEN-END:variables
}
