/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.QuizerDao;
import Entity.Quiz;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Muhammad Umer
 */
public class StudentView extends javax.swing.JFrame {

    /**
     * Creates new form StudentView
     */
    public StudentView() {
        initComponents();
        List<Quiz> quizlist=new ArrayList();
        QuizerDao qd=new QuizerDao();
        quizlist=qd.getQuizzes();
        Iterator itr=quizlist.iterator();
        while(itr.hasNext()){
            Quiz qz=(Quiz)itr.next();
            quizlistcombo.addItem(qz.getTitle());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attemptButton = new javax.swing.JButton();
        quizlistcombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attemptButton.setText("Attempt Quiz");
        attemptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptButtonActionPerformed(evt);
            }
        });
        getContentPane().add(attemptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, -1, -1));

        getContentPane().add(quizlistcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 641, -1));

        setSize(new java.awt.Dimension(677, 110));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void attemptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptButtonActionPerformed
        // TODO add your handling code here:
        String quiztitle=(String)quizlistcombo.getSelectedItem();
        TakingQuizView tqv=new TakingQuizView(quiztitle);
        tqv.setVisible(true);
        StudentView.this.dispose();
    }//GEN-LAST:event_attemptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attemptButton;
    private javax.swing.JComboBox<String> quizlistcombo;
    // End of variables declaration//GEN-END:variables

}
